<div class="important-links show_in_web">
  <div class="title services footTitle">
    <?= __('OUR SERVICES') ?>
  </div>
  <ul class="footer links  services-info opeinigClass">
    <li class="nav item ">
      <a href="<?= $this->getBaseUrl(); ?>privacy-policy" title="<?= __('Privacy Policy') ?>"><?= __('Privacy Policy') ?></a>
    </li>
    <li class="nav item ">
      <a href="<?= $this->getBaseUrl(); ?>terms-conditions" title="<?= __('Terms & Conditions') ?>"><?= __('Terms & Conditions') ?></a>
    </li>
    <li class="nav item">
      <a href="https://api.whatsapp.com/send/?phone=97460094446&text=Hi,%20Can%20you%20assist%20me?&app_absent=0" title="<?= __('Contact us') ?>" target="_blank"><?= __('Contact us') ?></a>
    </li>
    <li class="nav item">
      <a href="<?= $this->getBaseUrl(); ?>sales/guest/form" title="<?= __('Orders and Returns') ?>"><?= __('Orders and Returns') ?></a>
    </li>
    <li class="nav item">
      <a href="<?= $this->getBaseUrl(); ?>brand" title="<?= __('Brands') ?>"><?= __('Brands') ?></a>
    </li>
  </ul>
</div>
